version: "3.9"
services:
      nginx:
            image: nginx:latest
            container_name: nginx_container
            ports:
            - 80:80
            - 5005:5005
            volumes:
            - ./nginx/docker-nginx.conf:/etc/nginx/nginx.conf
      s3mock:
            image: adobe/s3mock
            ports: 
             - 9090:9090
             - 9191:9191
            environment:
                  initialBuckets: default
                  root: /data
                  retainFilesOnExit: true

      mongo:
            image: mongo:latest
            ports:
             - 27017:27017
            volumes:
                - type: volume
                  source: mongodb_data_volume_sentinel2_aws_db
                  target: /data/db
            environment:
                  MONGO_INITDB_ROOT_USERNAME: root
                  MONGO_INITDB_ROOT_PASSWORD: pass

volumes:
        mongodb_data_volume_sentinel2_aws_db:
